name: gitworkflow
run-name: sindhu

on:
  push:

jobs:
  gitjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        
      - name: DockerImage Build
        run: docker build -t sindhujajagarapu/newimage:newtag -f Dockerfile .
        
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push Docker Image
        run: docker push sindhujajagarapu/newimage:newtag 
      
